version: 2
updates:
  # Backend (Composer)
  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "minoru-kitayama"
    assignees:
      - "minoru-kitayama"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "composer"
      include: "scope"

  # Frontend (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "minoru-kitayama"
    assignees:
      - "minoru-kitayama"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "npm"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "minoru-kitayama"
    assignees:
      - "minoru-kitayama"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "minoru-kitayama"
    assignees:
      - "minoru-kitayama"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"